openapi: 3.0.1
info:
  title: Test-01
  description: Orchestratore Test 0.1
  version: '0.1'
servers:
  - url: http://localhost:8080/test/test01
    description: Generated server url
paths:
  /api/v1/ep01/{pathId}:
    post:
      tags:
        - Ex.01 - Orc.01
      summary: Ex.01 - Orc.01
      operationId: ep01
      parameters:
        - name: requestId
          in: header
          required: true
          schema:
            type: string
        - name: trackId
          in: header
          required: false
          schema:
            type: string
        - name: pathId
          in: path
          required: true
          schema:
            type: string
        - name: debug
          in: header
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orc01Request'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: BadRequest/Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBaseResponse'
              examples:
                response:
                  externalValue: "responseExamplesError.tmpl"
        '500':
          description: KO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  externalValue: "responseExamplesError.tmpl"
      x-symphony:
        id: orchestration1
        description: test N.1 - orchestration N.1
components:
  schemas:
    Ordinante:
      required:
        - codiceFiscale
        - natura
        - numero
        - tipologia
      type: object
      properties:
        natura:
          pattern: ^(CC|DR|DT|PP)$
          type: string
          description: |-
            Valori: 
            - CC - Conto
            - DR - Libretti
            - DT - DEBIT (Postamat)
            - PP - Carta
        tipologia:
          pattern: ^(ALIAS|RAPPORTO)$
          type: string
        numero:
          type: string
          description: Alias della carta, rapporto o numero del libretto che ha effettuato la ricarica
        codiceFiscale:
          pattern: ^([A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]|\d{11})$
          type: string
          description: Codice fiscale o partita iva dell'ordinante
        intestazione:
          type: string
    Orc01Request:
      required:
        - canale
        - ordinante
      type: object
      properties:
        canale:
          pattern: ^(APBP|NPDB|APDB|APPP|BPOL|PPAY|RPOL)$
          type: string
          description: |-
            Valori: 
            - APBP  app bp
            - NPDB  nuovo portale business
            - APDB  app business
            - APPP  app postepay
            - BPOL  web retail
            - PPAY  web postepay.it
            - RPOL  web risparmio postale
        ordinante:
          $ref: '#/components/schemas/Ordinante'
        additionalProperties:
          type: object
          additionalProperties:
            type: object
    BaseResponse:
      type: object
      properties:
        response_code: 
          type: string
        response_ip: 
          type: string
        kafkaResFromDict: 
          type: string
        numberAndDates: 
          type: object
          properties: 
            modifiedNumero: 
              type: string
            saldoDisponibile: 
              type: integer
              format: int32
            diffDateFromNow: 
              type: string
        modifiedArray: 
          type: array
          items: 
            type: object
            properties: 
              mod-a: 
                type: string
              mod-importo: 
                type: string
        attributiList: 
          type: object
          properties: 
            ATTR'5': 
              type: integer
              format: int32
            ATTR-3: 
              type: integer
              format: int32
            ATTR.4: 
              type: integer
              format: int32
            ATTR1: 
              type: integer
              format: int32
            ATTR2: 
              type: integer
              format: int32
        pathParam: 
          type: string
    ErrorBaseResponse:
      type: object
      properties:
        ambit:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
      nullable: true
    ErrorResponse:
      type: object
      #nullable: true
      properties:
        ambit:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        code:
          type: string
        description:
          type: string
        step:
          type: string
      nullable: true

